export const dummyData = [
  {
    name: "Tier Protocol",
    logo: "cardano-logo.svg",
    token: "XYZ",
    categories: ["DeFi", "Lending"],
    allocation: "20%",
    ratio: "0.00006%",
    takesRewards: "yes",
  },
  {
    name: "Mongosi City",
    logo: "cardano-logo.svg",
    token: "MCI",
    categories: ["Gaming"],
    allocation: "6%",
    ratio: "0.0000012%",
    takesRewards: "no",
  },
  {
    name: "Verbatum",
    logo: "cardano-logo.svg",
    token: "VTUM",
    categories: ["DeFi", "Dex"],
    allocation: "50%",
    ratio: "0.000135%",
    takesRewards: "yes",
  },
  {
    name: "Mara Market",
    logo: "cardano-logo.svg",
    token: "MARA",
    categories: ["NFT", "Marketplace"],
    allocation: "10%",
    ratio: "0.0000932%",
    takesRewards: "partial",
  },
  {
    name: "Zirum",
    logo: "cardano-logo.svg",
    token: "CZIR",
    categories: ["gaming"],
    allocation: "90%",
    ratio: "0.00932%",
    takesRewards: "optional",
  },
  {
    name: "Cardano Casino",
    logo: "cardano-logo.svg",
    token: "CACA",
    categories: ["gambling"],
    allocation: "1%",
    ratio: "0.00000000932%",
    takesRewards: "no",
  },
];
